//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PraktikaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match_Progress
    {
        public int ID_string_Progress { get; set; }
        public int ID_Match { get; set; }
        public int Shot_Id { get; set; }
        public int ID_Player { get; set; }
        public System.TimeSpan Minute { get; set; }
        public string Game_Score { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Shot Shot { get; set; }
        public virtual TennisPlayers TennisPlayers { get; set; }
    }
}
