//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PraktikaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match_Tennis_Player
    {
        public int ID_Match_Tennis_Player { get; set; }
        public int ID_Match { get; set; }
        public int ID_Player { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual TennisPlayers TennisPlayers { get; set; }
    }
}
