//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PraktikaWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Person_Profile
    {
        public int ID_Person { get; set; }
        [Required]
        [Display(Name ="Фамилия")]
        public string Surname_Profile { get; set; }
        [Required]
        [Display(Name = "Имя")]
        public string Name_Profile { get; set; }
      
        public string Email_Profile { get; set; }
    
        public virtual Passwords Passwords { get; set; }
    }
}
