//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PraktikaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tournament()
        {
            this.Start_Table = new HashSet<Start_Table>();
        }
    
        public int ID_Tournament { get; set; }
        public string Name_Tournament { get; set; }
        public int Type_Court { get; set; }
        public int Type_Tournament { get; set; }
        public decimal Prize_Money { get; set; }
        public Nullable<int> Match_info { get; set; }
        public int Country_info { get; set; }
        public System.DateTime Date_Start { get; set; }
        public System.DateTime Date_Finish { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Court Court { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Start_Table> Start_Table { get; set; }
    }
}
